//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOMComparer {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class MasterProperties : global::System.Configuration.ApplicationSettingsBase {
        
        private static MasterProperties defaultInstance = ((MasterProperties)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MasterProperties())));
        
        public static MasterProperties Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Son P/N Items")]
        public string partNumMBOM {
            get {
                return ((string)(this["partNumMBOM"]));
            }
            set {
                this["partNumMBOM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Location")]
        public string ReferenceMBOM {
            get {
                return ((string)(this["ReferenceMBOM"]));
            }
            set {
                this["ReferenceMBOM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("stx_num")]
        public string partNumNBOM {
            get {
                return ((string)(this["partNumNBOM"]));
            }
            set {
                this["partNumNBOM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Part Reference")]
        public string ReferenceNBOM {
            get {
                return ((string)(this["ReferenceNBOM"]));
            }
            set {
                this["ReferenceNBOM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QTY")]
        public string qtyMBOM {
            get {
                return ((string)(this["qtyMBOM"]));
            }
            set {
                this["qtyMBOM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Quantity")]
        public string qtyNBOM {
            get {
                return ((string)(this["qtyNBOM"]));
            }
            set {
                this["qtyNBOM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Description")]
        public string descMBOM {
            get {
                return ((string)(this["descMBOM"]));
            }
            set {
                this["descMBOM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Value")]
        public string descNBOM {
            get {
                return ((string)(this["descNBOM"]));
            }
            set {
                this["descNBOM"] = value;
            }
        }
    }
}
